/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as FriendsRouteRouteImport } from './routes/friends/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FriendsIndexRouteImport } from './routes/friends/index'
import { Route as FriendsFriendIdRouteImport } from './routes/friends/$friendId'

const FriendsRouteRoute = FriendsRouteRouteImport.update({
  id: '/friends',
  path: '/friends',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FriendsIndexRoute = FriendsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FriendsRouteRoute,
} as any)
const FriendsFriendIdRoute = FriendsFriendIdRouteImport.update({
  id: '/$friendId',
  path: '/$friendId',
  getParentRoute: () => FriendsRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/friends': typeof FriendsRouteRouteWithChildren
  '/friends/$friendId': typeof FriendsFriendIdRoute
  '/friends/': typeof FriendsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/friends/$friendId': typeof FriendsFriendIdRoute
  '/friends': typeof FriendsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/friends': typeof FriendsRouteRouteWithChildren
  '/friends/$friendId': typeof FriendsFriendIdRoute
  '/friends/': typeof FriendsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/friends' | '/friends/$friendId' | '/friends/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/friends/$friendId' | '/friends'
  id: '__root__' | '/' | '/friends' | '/friends/$friendId' | '/friends/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FriendsRouteRoute: typeof FriendsRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/friends': {
      id: '/friends'
      path: '/friends'
      fullPath: '/friends'
      preLoaderRoute: typeof FriendsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/friends/': {
      id: '/friends/'
      path: '/'
      fullPath: '/friends/'
      preLoaderRoute: typeof FriendsIndexRouteImport
      parentRoute: typeof FriendsRouteRoute
    }
    '/friends/$friendId': {
      id: '/friends/$friendId'
      path: '/$friendId'
      fullPath: '/friends/$friendId'
      preLoaderRoute: typeof FriendsFriendIdRouteImport
      parentRoute: typeof FriendsRouteRoute
    }
  }
}

interface FriendsRouteRouteChildren {
  FriendsFriendIdRoute: typeof FriendsFriendIdRoute
  FriendsIndexRoute: typeof FriendsIndexRoute
}

const FriendsRouteRouteChildren: FriendsRouteRouteChildren = {
  FriendsFriendIdRoute: FriendsFriendIdRoute,
  FriendsIndexRoute: FriendsIndexRoute,
}

const FriendsRouteRouteWithChildren = FriendsRouteRoute._addFileChildren(
  FriendsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FriendsRouteRoute: FriendsRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
